#!/usr/bin/env python3
"""
analyze_history.py — Mine your Claude Code history to see what you actually ask AI for.

Reads ~/.claude/projects/**/*.jsonl, extracts the FIRST human-typed message of each
session (your "opening intent"), separates automation-generated prompts from your own
hand-typed requests, and buckets the hand-typed ones by intent.

Usage:
    python3 analyze_history.py
    python3 analyze_history.py --root ~/.claude/projects --out intents.txt --samples 4

Note: AUTO_SIGNALS / BUCKETS are heuristics. Tune them for your own workflow.
"""
import argparse, json, os, glob, re, collections

# --- messages that are not real human prompts (system/tooling noise) -------------
NOISE_PREFIX = (
    "Caveat:", "<command-name>", "<command-message>", "<local-command",
    "<system-reminder>", "[Request interrupted", "This session is being continued",
    "API Error", "<bash-",
)

# --- signals that a "user" message was generated by your own automation, --------
# --- not typed by you. TUNE THIS for your pipelines (agent role headers, etc.). --
def is_automation(text: str) -> bool:
    head = text[:140].lower()
    # role-definition headers like "# Foo Agent\n## role ..."
    if text.startswith("#") and ("## role" in head or "agent" in head[:60] or "エージェント" in text[:60]):
        return True
    # structured template prompts (have explicit input/output scaffolding)
    for k in ("# 入力", "## input", "## 出力", "## output", "object literal", "json で出力"):
        if k in text[:160].lower() or k in text[:160]:
            return True
    return False

# --- intent buckets for hand-typed requests (multi-label). TUNE for your domain. -
BUCKETS = {
    "research/explain": ("調べ", "リサーチ", "research", "分析", "調査", "比較", "教えて",
                          "とは", "どう思", "なぜ", "検討", "investigate", "competitor", "市場"),
    "build/feature":    ("作って", "実装", "作成", "構築", "追加", "新規", "scaffold", "build",
                          "implement", "機能", "対応して"),
    "content/write":    ("記事", "note", "台本", "コピー", "文章", "ブログ", "投稿", "sns",
                          "ツイート", "リライト", "原稿", "write", "draft", "rewrite"),
    "video/media":      ("動画", "video", "reel", "shorts", "youtube", "ffmpeg", "remotion",
                          "サムネ", "ナレーション", "thumbnail"),
    "data/scrape":      ("スクレイ", "収集", "クロール", "csv", "抽出", "リスト化", "scrape",
                          "crawl", "extract", "一覧"),
    "review/audit":     ("レビュー", "確認して", "チェック", "監査", "診断", "評価", "review",
                          "audit", "見て"),
    "fix/debug":        ("エラー", "直し", "修正", "fix", "bug", "動かない", "落ちる", "バグ",
                          "原因", "失敗", "debug"),
    "deploy/infra":     ("デプロイ", "deploy", "本番", "公開して", "ビルド", "サーバ", "ssh",
                          "cron", "docker", "ci"),
    "test/qa":          ("テスト", "test", "qa", "網羅", "ケース", "coverage"),
    "strategy/biz":     ("戦略", "事業", "マネタイズ", "収益", "ビジネス", "参入", "撤退",
                          "構想", "アイデア", "strategy", "monetiz", "pricing"),
    "design/ui":        ("ui", "ux", "デザイン", "画面", "lp", "ランディング", "レイアウト",
                          "design", "layout"),
    "plan/manage":      ("計画", "todo", "タスク", "整理して", "まとめ", "ドキュメント",
                          "仕様", "ロードマップ", "plan", "spec"),
}


def first_human_intent(path: str):
    try:
        with open(path, errors="ignore") as fh:
            for i, line in enumerate(fh):
                if i > 80:
                    break
                try:
                    o = json.loads(line)
                except Exception:
                    continue
                if o.get("type") != "user" or o.get("isMeta"):
                    continue
                c = (o.get("message") or {}).get("content")
                txt = None
                if isinstance(c, str):
                    txt = c
                elif isinstance(c, list):
                    for b in c:
                        if isinstance(b, dict) and b.get("type") == "text":
                            txt = b.get("text")
                            break
                if not txt:
                    continue
                t = txt.strip()
                if not t or t.startswith(NOISE_PREFIX) or "tool_result" in t[:40]:
                    continue
                return re.sub(r"\s+", " ", t)
    except Exception:
        pass
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=os.path.expanduser("~/.claude/projects"))
    ap.add_argument("--out", default="intents.txt")
    ap.add_argument("--samples", type=int, default=4)
    args = ap.parse_args()

    files = glob.glob(os.path.join(args.root, "**", "*.jsonl"), recursive=True)
    intents = [h for h in (first_human_intent(f) for f in files) if h]
    auto = [t for t in intents if is_automation(t)]
    human = [t for t in intents if not is_automation(t)]

    print(f"sessions scanned : {len(files)}")
    print(f"automation prompts: {len(auto)}")
    print(f"hand-typed asks   : {len(human)}")

    with open(args.out, "w") as o:
        o.write("\n".join(h[:400] for h in human))
    print(f"\nhand-typed intents written to: {args.out}")

    assigned = collections.defaultdict(list)
    unmatched = []
    for t in human:
        tl = t.lower()
        hits = [b for b, ks in BUCKETS.items() if any(k.lower() in tl for k in ks)]
        if hits:
            for b in hits:
                assigned[b].append(t)
        else:
            unmatched.append(t)

    print("\n=== intent distribution (multi-label) ===")
    for b in sorted(assigned, key=lambda x: -len(assigned[x])):
        print(f"{len(assigned[b]):5d} | {b}")
    print(f"{len(unmatched):5d} | unmatched")

    import random
    random.seed(1)
    print(f"\n=== {args.samples} samples per bucket ===")
    for b in sorted(assigned, key=lambda x: -len(assigned[x])):
        print(f"\n### {b}")
        for s in random.sample(assigned[b], min(args.samples, len(assigned[b]))):
            print("  -", s[:110])


if __name__ == "__main__":
    main()
